<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.client_storage' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/Driver/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/Driver/InMemoryDriver.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/ClientStorageInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/ClientStorage.php';

$this->privates['gos_web_socket.client_storage'] = $instance = new \Gos\Bundle\WebSocketBundle\Client\ClientStorage(900, ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));

$instance->setStorageDriver(new \Gos\Bundle\WebSocketBundle\Client\Driver\InMemoryDriver());

return $instance;
