<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_pubsub_router.debug.command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Command/DebugRouterCommand.php';

$this->privates['gos_pubsub_router.debug.command'] = $instance = new \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand();

$instance->addRouter(($this->privates['gos_pubsub_router.websocket'] ?? $this->load('getGosPubsubRouter_WebsocketService.php')));
$instance->setName('gos:prouter:debug');

return $instance;
