<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.wamp.topic_manager' shared service.

include_once $this->targetDirs[3].'/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServerInterface.php';
include_once $this->targetDirs[3].'/vendor/cboden/ratchet/src/Ratchet/ComponentInterface.php';
include_once $this->targetDirs[3].'/vendor/cboden/ratchet/src/Ratchet/Wamp/WampServerInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Topic/TopicManager.php';

$this->privates['gos_web_socket.wamp.topic_manager'] = $instance = new \Gos\Bundle\WebSocketBundle\Topic\TopicManager();

$instance->setWampApplication(($this->privates['gos_web_socket_server.wamp_application'] ?? $this->load('getGosWebSocketServer_WampApplicationService.php')));

return $instance;
