<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_pubsub_router.collection.websocket' shared service.

include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Router/RouteCollection.php';

return $this->privates['gos_pubsub_router.collection.websocket'] = new \Gos\Bundle\PubSubRouterBundle\Router\RouteCollection();
