<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.server.event_loop' shared service.

include_once $this->targetDirs[3].'/vendor/react/event-loop/src/Factory.php';

return $this->privates['gos_web_socket.server.event_loop'] = \React\EventLoop\Factory::create();
