<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aMM1.kr' shared service.

return $this->privates['.service_locator.aMM1.kr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('game' => function (): \App\Entity\Game {
    return ($this->privates['.errored..service_locator.aMM1.kr.App\Entity\Game'] ?? $this->load('getGameService.php'));
}));
