<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.client_event.listener' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Event/ClientEventListener.php';

return $this->privates['gos_web_socket.client_event.listener'] = new \Gos\Bundle\WebSocketBundle\Event\ClientEventListener(($this->privates['gos_web_socket.client_storage'] ?? $this->load('getGosWebSocket_ClientStorageService.php')), ($this->privates['gos_web_socket.websocket_authentification.provider'] ?? $this->load('getGosWebSocket_WebsocketAuthentification_ProviderService.php')), ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));
