<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.aMM1.kr.App\Entity\Game' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.aMM1.kr": it references class "App\\Entity\\Game" but no such service exists.');
