<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket_server.wamp_application' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/Registry/RpcRegistry.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/Dispatcher/RpcDispatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/Dispatcher/RpcDispatcher.php';
include_once $this->targetDirs[3].'/vendor/cboden/ratchet/src/Ratchet/ComponentInterface.php';
include_once $this->targetDirs[3].'/vendor/cboden/ratchet/src/Ratchet/Wamp/WampServerInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/WampApplication.php';

$a = ($this->privates['gos_web_socket.topic.dispatcher'] ?? $this->load('getGosWebSocket_Topic_DispatcherService.php'));

if (isset($this->privates['gos_web_socket_server.wamp_application'])) {
    return $this->privates['gos_web_socket_server.wamp_application'];
}

return $this->privates['gos_web_socket_server.wamp_application'] = new \Gos\Bundle\WebSocketBundle\Server\App\WampApplication(new \Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\RpcDispatcher(new \Gos\Bundle\WebSocketBundle\Server\App\Registry\RpcRegistry()), $a, ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['gos_web_socket.client_storage'] ?? $this->load('getGosWebSocket_ClientStorageService.php')), ($this->privates['gos_web_socket.router.wamp'] ?? $this->load('getGosWebSocket_Router_WampService.php')), ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));
