<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.websocket_server.command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Command/WebsocketServerCommand.php';

$this->privates['gos_web_socket.websocket_server.command'] = $instance = new \Gos\Bundle\WebSocketBundle\Command\WebsocketServerCommand(($this->privates['gos_web_socket.entry_point'] ?? $this->load('getGosWebSocket_EntryPointService.php')), '127.0.0.1', 8080, ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));

$instance->setName('gos:websocket:server');

return $instance;
