<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.websocket' shared service.

$this->privates['monolog.handler.websocket'] = $instance = new \Symfony\Bridge\Monolog\Handler\ConsoleHandler(NULL, true, array(32 => 100, 16 => 400, 64 => 250, 128 => 200, 256 => 100));

$instance->pushProcessor(($this->privates['monolog.processor.psr_log_message'] ?? $this->privates['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor()));

return $instance;
