<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.websocket_authentification.provider' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/Auth/WebsocketAuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Client/Auth/WebsocketAuthenticationProvider.php';

return $this->privates['gos_web_socket.websocket_authentification.provider'] = new \Gos\Bundle\WebSocketBundle\Client\Auth\WebsocketAuthenticationProvider(($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()), $this->parameters['gos_web_socket.firewall'], ($this->privates['gos_web_socket.client_storage'] ?? $this->load('getGosWebSocket_ClientStorageService.php')), ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));
