<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.entry_point' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/Registry/ServerRegistry.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/EntryPoint.php';

$a = ($this->privates['gos_web_socket.ws.server'] ?? $this->load('getGosWebSocket_Ws_ServerService.php'));

if (isset($this->privates['gos_web_socket.entry_point'])) {
    return $this->privates['gos_web_socket.entry_point'];
}

$b = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\ServerRegistry();
$b->addServer($a);

return $this->privates['gos_web_socket.entry_point'] = new \Gos\Bundle\WebSocketBundle\Server\EntryPoint($b);
