<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_web_socket.pnctl_event.listener' shared service.

include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Event/StartServerListener.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Server/App/Registry/PeriodicRegistry.php';
include_once $this->targetDirs[3].'/vendor/gos/web-socket-bundle/Pusher/ServerPushHandlerRegistry.php';

return $this->privates['gos_web_socket.pnctl_event.listener'] = new \Gos\Bundle\WebSocketBundle\Event\StartServerListener(($this->privates['gos_web_socket.periodic.registry'] ?? $this->privates['gos_web_socket.periodic.registry'] = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\PeriodicRegistry()), ($this->privates['gos_web_socket.server_push_handler.registry'] ?? $this->privates['gos_web_socket.server_push_handler.registry'] = new \Gos\Bundle\WebSocketBundle\Pusher\ServerPushHandlerRegistry()), ($this->services['monolog.logger.websocket'] ?? $this->load('getMonolog_Logger_WebsocketService.php')));
