<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gos_pubsub_router.websocket' shared service.

include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Tokenizer/TokenizerInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Tokenizer/Tokenizer.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Tokenizer/TokenizerCacheDecorator.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Matcher/MatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Matcher/Matcher.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Generator/GeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Generator/Generator.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Router/RouterContext.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Router/RouterInterface.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Router/Router.php';
include_once $this->targetDirs[3].'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/Cache.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Cache/PhpFileCacheDecorator.php';
include_once $this->targetDirs[3].'/vendor/gos/pubsub-router-bundle/Router/RouteCollection.php';

$a = ($this->privates['gos_pubsub_router.collection.websocket'] ?? $this->privates['gos_pubsub_router.collection.websocket'] = new \Gos\Bundle\PubSubRouterBundle\Router\RouteCollection());

$b = new \Gos\Bundle\PubSubRouterBundle\Tokenizer\TokenizerCacheDecorator(new \Gos\Bundle\PubSubRouterBundle\Tokenizer\Tokenizer(), ($this->privates['gos_pubsub_router.php_file.cache'] ?? $this->privates['gos_pubsub_router.php_file.cache'] = new \Gos\Bundle\PubSubRouterBundle\Cache\PhpFileCacheDecorator($this->targetDirs[0], true)));

$c = new \Gos\Bundle\PubSubRouterBundle\Matcher\Matcher($b);
$c->setCollection($a);

$d = new \Gos\Bundle\PubSubRouterBundle\Generator\Generator($b);
$d->setCollection($a);

$this->privates['gos_pubsub_router.websocket'] = $instance = new \Gos\Bundle\PubSubRouterBundle\Router\Router($a, $c, $d, ($this->services['gos_pubsub_router.loader.websocket'] ?? $this->load('getGosPubsubRouter_Loader_WebsocketService.php')), 'websocket');

$e = new \Gos\Bundle\PubSubRouterBundle\Router\RouterContext();
$e->setTokenSeparator('/');

$instance->setContext($e);

return $instance;
