<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NQkGN7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NQkGN7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2NQkGN7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2NQkGN7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2NQkGN7\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2NQkGN7',
    'container.build_id' => 'de990696',
    'container.build_time' => 1536786992,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2NQkGN7');
