<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRftxQJF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRftxQJF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRftxQJF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRftxQJF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRftxQJF\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RftxQJF',
    'container.build_id' => 'b315de7f',
    'container.build_time' => 1537427113,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRftxQJF');
