<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIx1gqDK\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIx1gqDK/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIx1gqDK.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIx1gqDK\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIx1gqDK\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ix1gqDK',
    'container.build_id' => 'f54eb91c',
    'container.build_time' => 1536792239,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIx1gqDK');
